config/routes.rb
Rails.application.routes.draw do
  resources :contact_forms, :only => [:create]

  HighVoltage.configure do |config|
    config.home_page = 'home'
  end
end

app/models/contact_form.rb
class ContactForm < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_forms_controller.rb
class ContactFormsController < InheritedResources::Base
  def create
    @contact_form = ContactForm.new(contact_form_params)
    respond_to do |format|
      if @contact_form.save
        format.html { redirect_to @contact_form, notice: 'Contact was successfully created.' }
        format.json { render action: 'show', status: :created, location: @contact_form }
        format.js   { render :nothing => true, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact_form.errors, status: :unprocessable_entity }
        format.js   { render json: @contact_form.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def contact_form_params
      params.require(:contact_form).permit(:email, :name, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_IO_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.io/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_IO_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div id="flash">
    <% flash.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/contact_forms/_form.html.erb
<%= simple_form_for(@contact_form) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email %>
    <%= f.input :name %>
    <%= f.input :message %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/contact_forms/edit.html.erb
<h1>Editing Contact Form</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact_form %> |
<%= link_to 'Back', contact_forms_path %>

app/views/contact_forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contact Forms</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contact_forms.each do |contact_form| %>
      <tr>
        <td><%= contact_form.email %></td>
        <td><%= contact_form.name %></td>
        <td><%= contact_form.message %></td>
        <td><%= link_to 'Show', contact_form %></td>
        <td><%= link_to 'Edit', edit_contact_form_path(contact_form) %></td>
        <td><%= link_to 'Destroy', contact_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact form', new_contact_form_path %>

app/views/contact_forms/new.html.erb
<h1>New Contact Form</h1>

<%= render 'form' %>

<%= link_to 'Back', contact_forms_path %>

app/views/contact_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @contact_form.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @contact_form.name %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact_form.message %>
</p>

<%= link_to 'Edit', edit_contact_form_path(@contact_form) %> |
<%= link_to 'Back', contact_forms_path %>

app/views/layouts/_nav.html.erb
<div class="main-header">
  <%=link_to "Anuvis's Bio", "#page2", class: ""  %>
  <%=link_to "Experience", "#page3", class: ""  %>
  <%=link_to "Education", "#page4", class: "" %>
  <%=link_to "Skills", "#page5", class: "" %>
  <%=link_to "Contact Me", "#page6", class: "" %>
  <%#= render "flashes" -%>
  <div class="nav-links"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="ROBOTS" content="NOODP" />
    <meta name="viewport" content="initial-scale=1, width=device-width, maximum-scale=1, minimum-scale=1, user-scalable=no">
    <%# Configure default and controller-, and view-specific titles in config/locales/en.yml. For more see: https://github.com/calebthompson/title#usage %>
    <title><%= title %></title>

    <%= stylesheet_link_tag :application, media: "all" %>
    <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
    <!-- Fonts -->
    <script src="//use.typekit.net/zdl1usf.js"></script>
    <script>try{Typekit.load();}catch(e){}</script>
    <!-- Fonts End -->

    <%= csrf_meta_tags %>
  </head>

  <body>

    <header>
      <%= render 'layouts/nav' %>
    </header>

    <div id="fullpage">
      <%= yield %>
    </div>

    <script type="text/javascript">
      $(document).ready(function() {
          $('#fullpage').fullpage();
      });
    </script>

    <%#= javascript_include_tag 'application-btm' %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="section intro" data-anchor="home">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <h5></h5>
        <%= image_tag 'anuvisfull_02_02.svg', class: 'img-responsive intro-image' %>
        <h1>Anuvis Mejia</h1>
        <p>Full Stacks Ruby Web Developer - But it's always more than that.
         <!--  Hi, my names Anuvis Mejia a Miami based freelance web developer and designer. I passionately move pixels and lines of code to craft clean, responsive, and user-friendly websites. My current weapons of choice are Ruby on Rails, jQuery, and MySQL. Being both an engineer and designer, I help clients bring their ideas into reality. --></p>
        <br>
        <a href="#page2" class="btn btn-oye">More</a>
      </div>
    </div>
  </div>
</div>

<div class="section bio" data-anchor="page2">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <h1>Anuvis's Bio</h1>
        <p>
          Hi, my names Anuvis Mejia a Miami based freelance web developer and designer. I passionately move pixels and lines of code to craft clean, responsive, and user-friendly websites. My current weapons of choice are Ruby on Rails, jQuery, and MySQL. Being both an engineer and designer, I help clients bring their ideas into reality.
        </p>
        <br>
        <a href="#page3" class="btn btn-oye">More</a>
      </div>
    </div>
  </div>
</div>

<!-- <div class="section education" data-anchor="page3">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <h1>Experience</h1>
        <br>
        <a href="#page4" class="btn btn-oye">More</a>
      </div>
    </div>
  </div>
</div> -->

<div class="section education" data-anchor="page4">
  <div class="bkg"></div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <h1>Education</h1>
        <div class="education-carousel">
          <div> 
            <h2>Wyncode Academy</h2>
            <h5>Accelerated Web Development Program</h5>
            <p><strong>2014-2015</strong></p>
            <p>Wyncode Academy is a development boot camp immersing ambitious individuals in a demanding and inspiring learning environment engineered to develop successful coders with business acumen. We believe in promoting programming literacy using a disruptive education model and feel that a boot camp environment is the best way to learn practical and relevant coding skills quickly. http://www.wyncode.co/</p>
          </div>
          <div> 
            <h2>Florida International University</h2>
            <h5>Criminal Justice and Corrections</h5>
            <p><strong>2007-2011</strong></p>
          </div>
        </div>
        <br>
        <a href="#page5" class="btn btn-oye">More</a>
      </div>
    </div>
  </div>
</div>

<div class="section skills" data-anchor="page5">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <h1>Skills</h1>
        <h5>A concise list of some of the most valuable professional skills I possess. My tricks of the trade and what I can bring to the table.</h5>
        <div class="skills-carousel">
          <div>Ruby</div>
          <div>Postgress</div>
          <div>MySQL</div>
          <div>Ruby on Rails</div>
          <div>Jquery/Javascript</div>
          <div>CSS/SASS</div>
          <div>Git/Github</div>
          <div>Heroku</div>
          <div>Active Record</div>
          <div>Agile/Lean</div>
        </div>
        <br>
        <a href="#page6" class="btn btn-oye">More</a>
      </div>
    </div>
  </div>
</div>

<div class="section contact" data-anchor="page6">
  <div class="bkg"></div>
  <div class="container-fluid">
    <div class="col-sm-10 col-sm-offset-1">
      <div class="row">
        <div class="col-sm-5 col-sm-offset-1">
          <div class="contact-info">
            <div class="space50"></div>
            <h2>Contact Me</h2>
            <p>Have an Idea get in contact with me.</p>
            <a href="mailto:ameji012@gmail.com?Subject=Contact" target="_top"><i class="fa fa-envelope-square fa-2x"></i></a>
            <a href="https://www.linkedin.com/in/anuvism"><i class="fa fa-linkedin-square fa-2x"></i></a>
            <a href="https://www.facebook.com/anuvis.mejia"><i class="fa fa-facebook-square fa-2x"></i></a>
            <a href="https://twitter.com/Anuvis_M"><i class="fa fa-twitter-square fa-2x"></i></a>
            <a href="https://github.com/Ameji012"><i class="fa fa-github-square fa-2x"></i></a>
            <p><i class="fa fa-map-marker"></i> Miami, FL</p>
            
          </div>
        </div>
        <div class="col-sm-5">
          <div class="contact_form_shown">
            <%= simple_form_for ContactForm.new, remote: true, html: {class: "animated"} do |f| %>
              <%= f.error_notification %>
                <%= f.input :name, label: false, placeholder: "Name", input_html: {class: 'form-control'} %>
                <br>
                <%= f.input :email, label: false, placeholder: "Email", input_html: {class: 'form-control'} %>
                <br>
                <%= f.input :message, label: false, placeholder: "Message", as: :text, input_html: {class: 'form-control'}  %>
                <br>
                <%= f.button :submit, "Submit",:name => 'commit', :id=>"person_create_form_submit", class: 'btn btn-default'  %>
            <% end %>
          </div>
          <div class="contact_form_hidden" style="display:none;">
            <h2>Thanks</h2>
            <p>I will be in contact shortly</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<script type="text/javascript">
$('#new_contact_form').validate({
    rules: {
      "contact_form[name]": {required: true},
      "contact_form[email]": {required: true, email: true}
    }
  });
$('#person_create_form_submit').closest('form').on('ajax:success', function() {
    $(".contact_form_shown").hide()
    $(".contact_form_hidden").fadeIn(500)
  })
  $('#person_create_form_submit').closest('form').on('ajax:error', function() {
    $('.contact').prepend("<div><h4>Please check your submission.</h4></div>").css('color','red').fadeIn().fadeOut(200)
    $(this).addClass('shake');
  })
</script>

app/views/refills/_flashes.html.erb
<div class="flash-success">
  <span>This is a success message <a href="#">with a link</a></span>
</div>

<div class="flash-error">
  <span>This is an error message <a href="#">with a link</a></span>
</div>

<div class="flash-notice">
  <span>This is an notice message <a href="#">with a link</a></span>
</div>

<div class="flash-alert">
  <span>This is an alert message <a href="#">with a link</a></span>
</div>